### ISSUE TITLE
Learn from server conversations

### ISSUE THREAD

**Issue by danth** [danth/axyn#2]
Watch conversations happening in the server, and store them in the database for learning. Users should be able to enable/disable this feature on a per-server basis, with it being disabled by default. If a new user joins a server where it is enabled, they receive a warning via DM that their messages may be stored.

- [x] Learn from conversations
- [ ] Allow toggling
- [ ] Warn users that messages will be stored

**Comment by AlphaMycelium** [comment]
Could be a better idea to ask for permission on a per-user basis instead of having only a warning. It would be disabled by default, and when the user sends their first message, they receive a short description of what Axyn does and a command (`a!optin`?) to enable learning from their messages.
